name: Run Gradle Tests

on: [push]

jobs:
  build:

    name: Run Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@1.0
        with:
          graalvm-version: '19.2.0.1'
          
      - name: install GraalVM native-image
        run: gu install native-image

      - name: Run Tests with Gradle
        run: ./gradlew clean test functionalTest
