name: Run Gradle Tests

on: [push]

jobs:
  build:

    name: Run Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@latest
      - uses: DeLaGuardo/setup-graalvm@1.0
        with:
          graalvm-version: 19.2.1

      - name: Run Tests with Gradle
        run: ./gradlew clean functionalTest
