name: Release Plugin

on:
  push:
    tag:
      - "*"

jobs:
  build:
    name: Release Plugin
    runs-on: ubuntu-18.04

    steps:
      - name: calculate version
        run: echo "::set-output name=value::`echo $REF | tr '/' ' ' | awk '{print $3}'`"
        id: version
        env:
          REF: ${{ github.ref }}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '8.0.242'

      - name: Cache gradle
        id: gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Release to gradle plugin portal
        if: contains(github.ref, 'refs/tags/')
        env:
          PROJECT_VERSION: ${{ steps.version.outputs.value }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: |
          ./gradlew clean publishPlugins \
            -Pgradle.publish.key=$GRADLE_PUBLISH_KEY \
            -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET \
            -PpluginVersion=$PROJECT_VERSION

      - name: Show project version
        if: contains(github.ref, 'refs/heads')
        env:
          PROJECT_VERSION: ${{ steps.version.outputs.value }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: |
          ./gradlew clean showVersion \
            -Pgradle.publish.key=$GRADLE_PUBLISH_KEY \
            -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET \
            -PpluginVersion=$PROJECT_VERSION
