name: version availability test

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      memo:
        description: memo
        required: false

jobs:
  test:
    name: "Gradle-${{ matrix.version }} nativeImage"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version:
          - 6.6
          - 6.5.1
          - 6.4.1
          - 6.3
          - 6.2.2
          - 6.1.1

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: 20.2.0.java11

      - name: Install GraalVM native-image
        run: gu install native-image

      - name: Cache Gradle Wrapper
        id: gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: wrapper-${{ matrix.version }}
          restore-keys: wrapper-

      - name: Run Test
        run: ./version-tests/prepare.sh
        env:
          GRADLE_VERSION: ${{ matrix.version }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
